### ISSUE TITLE
The 'Sign Out' button in the ClientApp produces an error

### ISSUE THREAD

**Issue by peterwjames** [GoogleCloudPlatform/firebase-appengine-backend#5]
The app just crashes, without signing out:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.google.cloud.solutions.flexenv, PID: 3437
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.database.DatabaseReference.removeEventListener(com.google.firebase.database.ChildEventListener)' on a null object reference
                      at com.google.cloud.solutions.flexenv.PlayActivity$4.onResult(PlayActivity.java:243)
                      at com.google.cloud.solutions.flexenv.PlayActivity$4.onResult(PlayActivity.java:240)
                      at com.google.android.gms.internal.zznv$zza.zzb(Unknown Source)
                      at com.google.android.gms.internal.zznv$zza.handleMessage(Unknown Source)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by peterwjames** [comment]
Unable to recreate issue. Works fine now.
